"""Update Roles

Revision ID: 07b3f30deca6
Revises: 8109187d46bc
Create Date: 2026-03-26 22:28:59.058559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07b3f30deca6'
down_revision: Union[str, None] = '8109187d46bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('guest', 'authenticated_user', 'admin') NOT NULL DEFAULT 'authenticated_user'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('user', 'moderator', 'admin', 'super_admin') NOT NULL DEFAULT 'user'")
    op.alter_column('users', 'balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
