"""Add PromotionPackage and enums

Revision ID: 1156c8309548
Revises: 8a938cc8765f
Create Date: 2026-03-27 03:51:21.765870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1156c8309548'
down_revision: Union[str, None] = '8a938cc8765f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('promotion_type', sa.Enum('featured', 'boosted', 'top_feed', name='promotiontypeenum'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_packages_id'), 'promotion_packages', ['id'], unique=False)
    op.add_column('promotions', sa.Column('package_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'promotions', 'promotion_packages', ['package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.drop_column('promotions', 'package_id')
    op.drop_index(op.f('ix_promotion_packages_id'), table_name='promotion_packages')
    op.drop_table('promotion_packages')
    # ### end Alembic commands ###
